version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: daily
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "@schematics/angular"
      angular-security:
        applies-to: security-updates
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "@schematics/angular"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
