FROM eclipse-temurin:21-jre

WORKDIR /app/site

ENV KIDS_QUIZ_DATA_DIR=/data
ENV KIDS_QUIZ_DB_PATH=/data/kids-quiz.sqlite

COPY .kobweb ./.kobweb
COPY build/dist ./build/dist
COPY docker-entrypoint.sh /usr/local/bin/kids-quiz-entrypoint

RUN mkdir -p /data \
    && chmod +x ./.kobweb/server/start.sh /usr/local/bin/kids-quiz-entrypoint

EXPOSE 8080

ENTRYPOINT ["kids-quiz-entrypoint"]
